=== mappauk/prompt-based-structured-inference/data/coref/GENIA_MedCo_coreference_corpus_1.0/GENIA_coref_10.dtd
<!-- ============================================================ -->
<!-- DTD for Genia corpus with coref annotation                   -->
<!-- written by Jin-Dong KIM <jdkim@tsujii.is.s.u-tokyo.ac.jp>    -->
<!-- Date of last modification: August 1 2010                     -->
<!-- ============================================================ -->

<!-- ============================================================ -->
<!-- Labels for coref types                                       -->
<!-- ============================================================ -->

<!ENTITY % coref.type "(APPOS | IDENT | OTHERS | PRON | RELAT | PART-WHOLE | WHOLE-PART | OTHER)">

<!-- ============================================================ -->
<!-- HIERARCHICAL ELEMENTS                                        -->
<!-- ============================================================ -->
<!ELEMENT Annotation (PubmedArticleSet)>
<!ATTLIST Annotation
		annotates CDATA #IMPLIED
		creator   CDATA #IMPLIED
		created   CDATA #IMPLIED
>

<!ELEMENT PubmedArticleSet (PubmedArticle)>
<!ELEMENT PubmedArticle (MedlineCitation)>
<!ELEMENT MedlineCitation (PMID, Article)>
<!ELEMENT Article (ArticleTitle?, Abstract)>
<!ELEMENT Abstract (AbstractText)>

<!-- ============================================================ -->
<!-- BLOCK ELEMENTS                                               -->
<!-- ============================================================ -->
<!ELEMENT ArticleTitle (sentence)+>
<!ELEMENT AbstractText (sentence)+>
<!ELEMENT PMID (#PCDATA)>

<!-- ============================================================ -->
<!-- LINGUISTIC ELEMENTS                                          -->
<!-- ============================================================ -->
<!ELEMENT sentence	(#PCDATA | coref)*>
<!ATTLIST sentence	id ID	#REQUIRED>

<!ELEMENT coref (#PCDATA | coref)*>
<!ATTLIST coref
		id	ID		#REQUIRED
		ref	IDREFS		#IMPLIED
		type	%coref.type;	#IMPLIED
		min	CDATA		#IMPLIED
		target	CDATA		#IMPLIED
		check	CDATA		#IMPLIED
>

=== mappauk/prompt-based-structured-inference/data/coref/GENIA_MedCo_coreference_corpus_1.0/test/9192770.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION COREF 1.0//EN" "GENIA_coref_10.dtd">
<?xml-stylesheet type="text/css" href="GENIA_coref_10.css"?>
<Annotation annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;amp;retmode=xml&amp;amp;rettype=medline&amp;amp;id=9192770">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>9192770</PMID>
<Article>
<ArticleTitle>
<sentence id="S1"><coref id="C1">Interleukin-10</coref> inhibits <coref min="transcription" id="C2">interferon-gamma-induced intercellular adhesion molecule-1 gene transcription</coref> in human monocytes.</sentence>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2"><coref ref="C1" type="IDENT" id="C3">Interleukin-10 (IL-10)</coref> is <coref ref="C3" min="cytokine" type="IDENT" id="C4"><coref min="cytokine" id="C5">a potent monocyte regulatory cytokine</coref> <coref ref="C5" type="RELAT" id="C6">that</coref> inhibits gene expression of proinflammatory mediators</coref>.</sentence>
<sentence id="S3">In this study, we investigated <coref id="C7">the mechanism</coref> by <coref ref="C7" type="RELAT" id="C8">which</coref> <coref ref="C4" type="IDENT" id="C9">IL-10</coref> downregulates <coref min="expression" type="IDENT" id="C10">expression of intercellular adhesion molecule-1 (ICAM-1)</coref> on the cell surface of <coref min="monocytes" id="C11">normal human monocytes activated with interferon-gamma (IFN-gamma)</coref>.</sentence>
<sentence id="S4">IL-10 inhibition of <coref ref="C10" min="expression" type="IDENT" id="C12">IFN-gamma-induced ICAM-1 expression</coref> was apparent as early as 3 hours and was blocked by an anti-IL-10 antibody but not by an isotype-matched control antibody.</sentence>
<sentence id="S5">Northern blot analysis showed that <coref ref="C9" type="IDENT" id="C13">IL-10</coref> reduced the accumulation of ICAM-1 mRNA in <coref ref="C11" min="monocytes" type="IDENT" id="C14">IFN-gamma-stimulated monocytes</coref>.</sentence>
<sentence id="S6">IL-10 inhibition of ICAM-1 steady-state mRNA was detected at 3 hours and remained at 24 hours.</sentence>
<sentence id="S7">Nuclear run-on transcription assays showed that <coref ref="C13" type="IDENT" id="C15">IL-10</coref> inhibited the rate of <coref ref="C2" min="transcription" type="IDENT" id="C16">IFN-gamma-induced transcription of <coref min="gene" type="IDENT" id="C17">the ICAM-1 gene</coref></coref>, and mRNA stability studies showed that <coref ref="C15" type="IDENT" id="C18">IL-10</coref> did not alter the half-life of IFN-gamma-induced ICAM-1 message.</sentence>
<sentence id="S8">Thus, <coref ref="C18" type="IDENT" id="C19">IL-10</coref> inhibits <coref ref="C12" min="expression" type="IDENT" id="C20">IFN-gamma-induced ICAM-1 expression</coref> in monocytes primarily at the level of gene transcription.</sentence>
<sentence id="S9">Activation of IFN-gamma-responsive genes requires tyrosine phosphorylation of the transcriptional factor STAT-1alpha (signal transducer and activator of transcription-1alpha).</sentence>
<sentence id="S10">However, <coref ref="C19" type="IDENT" id="C21">IL-10</coref> did not affect IFN-gamma-induced tyrosine phosphorylation of STAT-1alpha or alter STAT-1alpha binding to the IFN-gamma response element (IRE) in <coref min="promoter" id="C22">the ICAM-1 promoter</coref>.</sentence>
<sentence id="S11">Instead, <coref ref="C21" type="IDENT" id="C23">IL-10</coref> prevented IFN-gamma-induced binding activity at the NF-kappaB site of the tumor necrosis factor alpha (TNF-alpha)-responsive NF-kappaB/C-EBP composite element in <coref ref="C22" min="promoter" type="IDENT" id="C24">the ICAM-1 promoter</coref>.</sentence>
<sentence id="S12">These data indicate that <coref ref="C23" type="IDENT" id="C25">IL-10</coref> inhibits <coref ref="C16" min="transcription" type="IDENT" id="C26">IFN-gamma-induced transcription of <coref ref="C17" min="gene" type="IDENT" id="C27">the ICAM-1 gene</coref></coref> by <coref min="mechanism" id="C28">a regulatory mechanism</coref> <coref ref="C28" type="RELAT" id="C29">that</coref> may involve NF-kappaB.</sentence>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>

=== mappauk/prompt-based-structured-inference/data/coref/GENIA_MedCo_coreference_corpus_1.0/test/8910577.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION COREF 1.0//EN" "GENIA_coref_10.dtd">
<?xml-stylesheet type="text/css" href="GENIA_coref_10.css"?>
<Annotation annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;amp;retmode=xml&amp;amp;rettype=medline&amp;amp;id=8910577">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>8910577</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">Identification and characterization of a leukocyte-specific component of <coref id="C1">the nuclear body</coref>.</sentence>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2"><coref ref="C1" type="IDENT" id="C2">The nuclear body (NB)</coref> is <coref id="C3">a cellular organelle</coref> <coref ref="C3" type="RELAT" id="C4">that</coref> is involved in the pathogenesis of acute promyelocytic leukemia and viral infection.</sentence>
<sentence id="S3"><coref ref="C2" type="IDENT" id="C5">The NB</coref> is also a target of antibodies in the serum of patients with <coref min="disease" id="C6">the autoimmune disease primary biliary cirrhosis</coref>.</sentence>
<sentence id="S4">In this study, serum from a patient with <coref ref="C6" type="IDENT" id="C7">primary biliary cirrhosis</coref> was used to identify a cDNA encoding <coref min="component" id="C9">a novel component of <coref ref="C5" type="IDENT" id="C8">the NB</coref></coref>, <coref ref="C9" type="APPOS" id="C10">a 140-kDa protein designated Sp140</coref>.</sentence>
<sentence id="S5">The predicted amino acid sequence of the amino-terminal portion of <coref id="C13">Sp140</coref> was similar to <coref id="C11">Sp100</coref>, <coref ref="C11" min="protein" type="APPOS" id="C12">a previously identified NB protein</coref>.</sentence>
<sentence id="S6">The carboxyl portion of <coref ref="C13" type="IDENT" id="C15">Sp140</coref> contained <coref id="C16">a zinc-finger domain and a bromodomain</coref>, <coref id="C17"><coref ref="C16" min="motifs" type="APPOS" id="C19">motifs</coref> <coref ref="C17" type="RELAT" id="C18">that</coref> are present in proteins regulating gene transcription</coref>.</sentence>
<sentence id="S7">High levels of <coref id="C20">Sp140 mRNA</coref> were detected in human spleen and peripheral blood leukocytes, but not other human tissues.</sentence>
<sentence id="S8">The level of <coref ref="C20" type="IDENT" id="C21">SP140 mRNA</coref> in myeloid precursor cell lines HL60 and NB4 markedly increased in response to chemically induced cellular differentiation.</sentence>
<sentence id="S9">Immunohistochemical techniques were used to demonstrate that <coref ref="C15" type="IDENT" id="C22">SP140</coref> localized to <coref ref="C5" type="IDENT" id="C23">the NB</coref> in differentiated HL60 and NB4 cells.</sentence>
<sentence id="S10">The location of <coref ref="C22" type="IDENT" id="C25">Sp140</coref> in <coref ref="C23" type="IDENT" id="C26">the NB</coref>, and expression of <coref ref="C25" type="IDENT" id="C27">this gene</coref> in cells involved in host defense, suggest that <coref ref="C25" type="IDENT" id="C28">Sp140</coref> may be involved in the pathogenesis of acute promyelocytic leukemia and viral infection.</sentence>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>

=== mappauk/prompt-based-structured-inference/data/coref/GENIA_MedCo_coreference_corpus_1.0/test/8995244.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION COREF 1.0//EN" "GENIA_coref_10.dtd">
<?xml-stylesheet type="text/css" href="GENIA_coref_10.css"?>
<Annotation annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;amp;retmode=xml&amp;amp;rettype=medline&amp;amp;id=8995244">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>8995244</PMID>
<Article>
<ArticleTitle>
<sentence id="S1"><coref min="transcription factor" id="C1">A novel transcription factor</coref> regulates expression of <coref min="subunit" id="C2">the vacuolar H+-ATPase B2 subunit</coref> through AP-2 sites during <coref min="differentiation" id="C3">monocytic differentiation</coref>.</sentence>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2">During <coref min="differentiation" id="C4">monocyte-to-macrophage differentiation</coref>, the cellular content of <coref id="C5">vacuolar H+-ATPase (V-ATPase)</coref> increases more than 4-fold.</sentence>
<sentence id="S3">We have shown previously that <coref min="expression" id="C6">amplified expression of <coref ref="C2" min="subunit" type="IDENT" id="C7">the B2 subunit of <coref ref="C5" type="IDENT" id="C8">the V-ATPase</coref></coref></coref> occurs solely by increased transcription, and that the 5'-untranslated region of the B2 gene, containing multiple consensus binding sites for the transcription factors AP-2 and Sp1, is required for <coref ref="C6" min="expression" type="IDENT" id="C9">this expression</coref>.</sentence>
<sentence id="S4">The present study demonstrates that AP-2 binding sequences are essential for increased transcription from <coref min="promoter" id="C10">the B2 promoter</coref> during <coref ref="C4" min="differentiation" type="IDENT" id="C11">monocyte-macrophage differentiation</coref> and that <coref id="C12">AP-2</coref>, expressed exogenously in THP-1 and other cells, activates transcription from <coref ref="C10" min="promoter" type="IDENT" id="C13">the B2 promoter</coref>.</sentence>
<sentence id="S5">In mobility shift assays, <coref min="factor" id="C14">a nuclear factor from THP-1 and U-937 cells</coref> was identified <coref ref="C14" type="RELAT" id="C15">that</coref> binds to several AP-2 response elements within <coref ref="C13" min="promoter" type="IDENT" id="C16">the B2 promoter</coref>, but does not react with AP-2 antibodies, and has <coref min="profile" id="C17">a DNA sequence binding affinity profile</coref> <coref ref="C17" type="RELAT" id="C18">that</coref> differs from <coref ref="C12" type="IDENT" id="C19">AP-2</coref>.</sentence>
<sentence id="S6">These findings suggest that <coref ref="C1" min="translcription-factor" type="IDENT" id="C20">a novel AP-2-like transcription factor</coref> is responsible for V-ATPase B subunit amplification during <coref ref="C3" min="differentiation" type="IDENT" id="C21">monocyte differentiation</coref>.</sentence>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>

=== mappauk/prompt-based-structured-inference/data/coref/GENIA_MedCo_coreference_corpus_1.0/test/7930570.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION COREF 1.0//EN" "GENIA_coref_10.dtd">
<?xml-stylesheet type="text/css" href="GENIA_coref_10.css"?>
<Annotation annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;amp;retmode=xml&amp;amp;rettype=medline&amp;amp;id=7930570">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>7930570</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">Simultaneous activation of <coref id="C1">Ig</coref> and Oct-2 synthesis and reduction of <coref id="C2">surface MHC class II expression</coref> by IL-6.</sentence>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2"><coref id="C3">Terminal differentiation of B cells</coref> to <coref id="C4">plasma cells</coref> in vivo is characterized by <coref id="C5">secretion of <coref ref="C1" type="IDENT" id="C6">Ig</coref></coref> and extinction of <coref ref="C2" min="expression" type="IDENT" id="C7">MHC class II expression</coref> on the cell surface.</sentence>
<sentence id="S3">We show that IL-6 signaling leads to marked increases in the synthesis and <coref ref="C5" min="secretion" type="IDENT" id="C8">secretion of <coref ref="C6" type="IDENT" id="C9">Ig</coref></coref> in clonal human B cell lines and newly isolated polyclonal B lymphocytes in vitro.</sentence>
<sentence id="S4">The IL-6-induced cells resemble <coref ref="C4" min="cells" type="IDENT" id="C10">plasma cells</coref> in ultrastructure and in reduced expression of surface MHC class II.</sentence>
<sentence id="S5">Enhanced Ig synthesis is a result of coordinated transcriptional activation of <coref ref="C9" type="IDENT" id="C11">Ig genes</coref> without promoter or isotype specificity, and differential accumulation of the mRNA encoding the secreted form of Ig heavy chain.</sentence>
<sentence id="S6">It is saturable and subject to negative control when IL-6 stimulation is prolonged.</sentence>
<sentence id="S7">Coordinate with temporal changes in Ig synthesis, the DNA-binding activity and the synthesis of <coref id="C12">the B cell-enriched transcription factor Oct-2</coref> are regulated.</sentence>
<sentence id="S8">Thus, differentiation of B cells with IL-6 in vitro recapitulates the hallmarks of <coref ref="C3" min="differentiation" type="IDENT" id="C13">terminal B differentiation</coref> in vivo; <coref ref="C12" type="IDENT" id="C14">Oct-2</coref> may have a role in <coref ref="C13" type="IDENT" id="C15">this process</coref>.</sentence>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>

=== mappauk/prompt-based-structured-inference/data/coref/GENIA_MedCo_coreference_corpus_1.0/test/10203577.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION COREF 1.0//EN" "GENIA_coref_10.dtd">
<?xml-stylesheet type="text/css" href="GENIA_coref_10.css"?>
<Annotation annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;amp;retmode=xml&amp;amp;rettype=medline&amp;amp;id=10203577">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>10203577</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">Suppressive effects of <coref min="agents" id="C1">anti-inflammatory agents</coref> on human endothelial cell activation and induction of heat shock proteins.</sentence>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2">BACKGROUND: Studies from our laboratory have shown that the earliest stages of atherosclerosis may be mediated by an autoimmune reaction against <coref id="C2">heat shock protein 60 (Hsp60)</coref>.</sentence>
<sentence id="S3">The interactions of Hsp60-specific T cells with arterial endothelial cells (EC) require expression of both Hsp60 and certain adhesion molecules shown to be induced simultaneously in <coref id="C3">EC</coref> by mechanical and other types of stress.</sentence>
<sentence id="S4">Recently, it was shown that suppression of T cell-mediated immune responses by <coref id="C4">cyclosporin A (CyA)</coref> enhanced atherosclerotic lesion formation in mice.</sentence>
<sentence id="S5">In contrast, <coref id="C5">aspirin</coref> was found to lower the risk of myocardial infarction in men.</sentence>
<sentence id="S6">These conflicting observations may be due to different effects of <coref ref="C1" min="agents" type="IDENT" id="C6">anti-inflammatory agents</coref> on adhesion molecule and Hsp expression in <coref ref="C3" type="IDENT" id="C7">EC</coref>, respectively.</sentence>
<sentence id="S7">MATERIAL AND METHODS: In the present study, we analyzed the effects of <coref id="C8"><coref ref="C4" type="IDENT" id="C9">CyA</coref>, <coref ref="C5" type="IDENT" id="C10">aspirin</coref>, and <coref id="C11">indomethacin</coref></coref> on <coref min="proliferation" id="C12">T cell proliferation</coref> using a proliferation assay.</sentence>
<sentence id="S8">To explore the expression of <coref min="molecules" id="C13">adhesion molecules</coref>, <coref ref="C13" type="APPOS" id="C14">monocyte chemoattractant protein-1 (MCP-1), and <coref min="hsp60" id="C15">Hsp60 in <coref min="cells" id="C16">human umbilical vein endothelial cells (HUVECs)</coref></coref></coref>, Northern blot analyses were used.</sentence>
<sentence id="S9">To examine the activation status of the transcription factors nuclear factor kappaB (NF-kappaB) and heat shock factor-1 (HSF-1), electrophoretic mobility shift assays were performed.</sentence>
<sentence id="S10">RESULTS: With the exception of <coref ref="C11" type="IDENT" id="C17">indomethacin</coref>, the used immunosuppressive and anti-inflammatory agents significantly inhibited <coref ref="C12" min="proliferation" type="IDENT" id="C18">T cell proliferation</coref> in response to influenza virus antigen in a dose-dependent manner.</sentence>
<sentence id="S11">Interestingly, <coref ref="C9" type="IDENT" id="C19">CyA</coref> and <coref ref="C17" type="IDENT" id="C20">indomethacin</coref> did not suppress tumor necrosis factor-alpha (TNF-alpha)-induced adhesion molecule expression on <coref ref="C16" type="IDENT" id="C21">HUVECs</coref>, whereas <coref ref="C10" type="IDENT" id="C22">aspirin</coref> had an inhibitory effect.</sentence>
<sentence id="S12">These observations correlated with the modulation of NF-kappaB activity in <coref ref="C7" type="IDENT" id="C23">EC</coref>.</sentence>
<sentence id="S13"><coref ref="C8" min="agents" type="IDENT" id="C24">All agents tested</coref> induced <coref min="expression" id="C25">expression of <coref ref="C2" type="IDENT" id="C26">Hsp60</coref></coref> 6 hr after application.</sentence>
<sentence id="S14">In addition, <coref ref="C22" type="IDENT" id="C27">aspirin</coref> and <coref ref="C20" type="IDENT" id="C28">indomethacin</coref>, but not <coref ref="C19" type="IDENT" id="C29">CyA</coref>, induced <coref min="expression" id="C30">Hsp70 expression in <coref ref="C21" type="IDENT" id="C31">HUVECs</coref></coref> <coref ref="C30" type="RELAT" id="C32">that</coref> correlated with induction of HSF-1 activity.</sentence>
<sentence id="S15">CONCLUSION: Our results show that the tested agents (except indomethacin) are inhibitors of the T cell-mediated immune response, as expected, that <coref ref="C27" type="IDENT" id="C33">aspirin</coref> is an effective suppressor of adhesion molecule expression, and that <coref ref="C24" min="agents" type="IDENT" id="C34">all three agents</coref> can induce <coref ref="C15" min="hsp60" type="IDENT" id="C35">Hsp60 in <coref ref="C31" type="IDENT" id="C36">HUVECs</coref></coref>.</sentence>
<sentence id="S16">These data provide the molecular basis for <coref id="C37">the notion</coref> <coref ref="C37" type="RELAT" id="C38">that</coref> (1) part of the anti-atherogenic effect of <coref ref="C33" type="IDENT" id="C39">aspirin</coref> may be due to the prevention of the adhesion of sensitized T cells to <coref min="ec" id="C40">stressed EC;</coref> (2) that part of the atherosclerosis-promoting effect of <coref ref="C29" type="IDENT" id="C41">CyA</coref> may be due to <coref ref="C41" type="PRON" id="C42">its</coref> potential as an inducer of <coref ref="C25" min="expression" type="IDENT" id="C43">Hsp60 expression</coref> and <coref ref="C41" type="PRON" id="C44">its</coref> inability to down-regulate adhesion molecule expression on <coref ref="C23" type="IDENT" id="C45">EC;</coref> and (3) that down-regulation of MCP-1 expression by <coref ref="C39" type="IDENT" id="C46">aspirin</coref> may result in decreased recruitment of monocytes into the arterial intima beneath <coref ref="C40" min="ec" type="IDENT" id="C47">stressed EC</coref>.</sentence>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>

=== mappauk/prompt-based-structured-inference/data/coref/GENIA_MedCo_coreference_corpus_1.0/test/10446065.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION COREF 1.0//EN" "GENIA_coref_10.dtd">
<?xml-stylesheet type="text/css" href="GENIA_coref_10.css"?>
<Annotation annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;amp;retmode=xml&amp;amp;rettype=medline&amp;amp;id=10446065">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>10446065</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">Transcriptional inhibition by <coref id="C21">interleukin-6</coref> of <coref min="receptor" id="C2">the class A macrophage scavenger receptor</coref> in <coref min="macrophages" id="C3">macrophages derived from human peripheral monocytes and the THP-1 monocytic cell line</coref>.</sentence>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2">Expression of <coref ref="C2" min="receptor" type="IDENT" id="C1">the class A macrophage scavenger receptor (MSR)</coref> contributes to the uptake of <coref min="lipoproteins" id="C23">modified low density lipoproteins (LDL)</coref> by <coref id="C4">macrophages</coref> and transformation of <coref ref="C23" type="IDENT" id="C24">these cells</coref> into <coref min="cells" id="C25">lipid-laden foam cells</coref>, <coref ref="C25" type="RELAT" id="C26">which</coref> characterize atherosclerosis.</sentence>
<sentence id="S3"><coref min="factors" id="C27">Many environmental factors</coref>, in particular, <coref ref="C27" min="factors" type="PART-WHOLE" id="C28">proinflammatory cytokines and growth factors</coref>, can exert regulatory effects on MSR expression, whereas <coref min="accumulation" id="C30">intracellular accumulation of cholesterol</coref> <coref ref="C30" type="PRON" id="C29">itself</coref> does not influence MSR levels to any considerable extent.</sentence>
<sentence id="S4">In the present study, by using an in vitro model, we examined whether stimulation with <coref ref="C21" type="IDENT" id="C31">interleukin-6 (IL-6)</coref>, <coref ref="C31" min="cytokine" type="APPOS" id="C32">an immunoregulatory, multipotential cytokine</coref>, modulates the expression and activities of <coref ref="C1" min="msr" type="IDENT" id="C7">the MSR</coref> in <coref ref="C4" type="IDENT" id="C8">macrophages</coref>.</sentence>
<sentence id="S5">When treated with <coref ref="C31" type="IDENT" id="C22">IL-6</coref>, <coref ref="C3" min="macrophages" type="IDENT" id="C9">macrophages derived from peripheral monocytes and phorbol 12-myristate 13-acetate (PMA)-differentiated THP-1 monocytic cells</coref> showed significantly reduced uptake and/or binding of <coref min="ligand" id="C33">the MSR ligand</coref>, <coref ref="C33" min="ldl" type="APPOS" id="C34">acetylated LDL</coref>.</sentence>
<sentence id="S6">This effect was paralleled by a reduction in the expression of MSR protein and mRNA.</sentence>
<sentence id="S7">Analysis of MSR promoter activity in THP-1 cells transfected with an <coref min="promotor" id="C16">MSR promoter-</coref>reporter gene construct demonstrated decreased activity of <coref ref="C16" min="promotor" type="IDENT" id="C17">the MSR promoter</coref> in <coref ref="C22" type="IDENT" id="C35">IL-6-</coref>treated THP-1 macrophages.</sentence>
<sentence id="S8">Electrophoretic mobility gel shift assay also showed a reduction in the binding of a transcription factor to the MSR promoter AP-1/ets elements in <coref ref="C35" type="IDENT" id="C36">IL-6-</coref>treated cells.</sentence>
<sentence id="S9">Thus, exposure to <coref ref="C36" type="IDENT" id="C37">IL-6</coref> may inhibit expression of <coref ref="C1" type="IDENT" id="C20">the class A MSR</coref> in differentiated macrophages at transcriptional levels.</sentence>
<sentence id="S10">This result suggests that <coref ref="C37" type="IDENT" id="C38">this cytokine</coref> may modulate foam cell formation during atherogenesis.</sentence>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>
