=== mappauk/prompt-based-structured-inference/data/coref/GENIA_MedCo_coreference_corpus_1.0/GENIA_coref_10.dtd
<!-- ============================================================ -->
<!-- DTD for Genia corpus with coref annotation                   -->
<!-- written by Jin-Dong KIM <jdkim@tsujii.is.s.u-tokyo.ac.jp>    -->
<!-- Date of last modification: August 1 2010                     -->
<!-- ============================================================ -->

<!-- ============================================================ -->
<!-- Labels for coref types                                       -->
<!-- ============================================================ -->

<!ENTITY % coref.type "(APPOS | IDENT | OTHERS | PRON | RELAT | PART-WHOLE | WHOLE-PART | OTHER)">

<!-- ============================================================ -->
<!-- HIERARCHICAL ELEMENTS                                        -->
<!-- ============================================================ -->
<!ELEMENT Annotation (PubmedArticleSet)>
<!ATTLIST Annotation
		annotates CDATA #IMPLIED
		creator   CDATA #IMPLIED
		created   CDATA #IMPLIED
>

<!ELEMENT PubmedArticleSet (PubmedArticle)>
<!ELEMENT PubmedArticle (MedlineCitation)>
<!ELEMENT MedlineCitation (PMID, Article)>
<!ELEMENT Article (ArticleTitle?, Abstract)>
<!ELEMENT Abstract (AbstractText)>

<!-- ============================================================ -->
<!-- BLOCK ELEMENTS                                               -->
<!-- ============================================================ -->
<!ELEMENT ArticleTitle (sentence)+>
<!ELEMENT AbstractText (sentence)+>
<!ELEMENT PMID (#PCDATA)>

<!-- ============================================================ -->
<!-- LINGUISTIC ELEMENTS                                          -->
<!-- ============================================================ -->
<!ELEMENT sentence	(#PCDATA | coref)*>
<!ATTLIST sentence	id ID	#REQUIRED>

<!ELEMENT coref (#PCDATA | coref)*>
<!ATTLIST coref
		id	ID		#REQUIRED
		ref	IDREFS		#IMPLIED
		type	%coref.type;	#IMPLIED
		min	CDATA		#IMPLIED
		target	CDATA		#IMPLIED
		check	CDATA		#IMPLIED
>

=== mappauk/prompt-based-structured-inference/data/coref/GENIA_MedCo_coreference_corpus_1.0/test/2137831.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION COREF 1.0//EN" "GENIA_coref_10.dtd">
<?xml-stylesheet type="text/css" href="GENIA_coref_10.css"?>
<Annotation annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;amp;retmode=xml&amp;amp;rettype=medline&amp;amp;id=2137831">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>2137831</PMID>
<Article>
<ArticleTitle>
<sentence id="S1"><coref id="C1">Pseudohypoaldosteronism</coref> in <coref min="families" id="C2">eight families</coref>: different forms of inheritance are evidence for <coref min="defects" id="C3">various genetic defects</coref>.</sentence>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2"><coref ref="C1" type="IDENT" id="C4">Pseudohypoaldosteronism</coref> is a rare hereditary disorder presenting in early infancy with renal salt loss leading to hyponatremia and hyperkalemia despite high levels of plasma aldosterone.</sentence>
<sentence id="S3">The patients are insensitive to <coref id="C5">mineralocorticoids</coref>; however, sodium supplementation is able to correct electrolyte abnormalities.</sentence>
<sentence id="S4">Absent or greatly diminished type I aldosterone receptors in <coref id="C6">peripheral mononuclear leucocytes</coref> have been recently demonstrated and explain the lack of response to <coref ref="C5" type="IDENT" id="C7">mineralocorticoids</coref>.</sentence>
<sentence id="S5">We have studied the mode of inheritance in <coref ref="C2" min="families" type="IDENT" id="C8">eight families</coref> with a total of nine patients.</sentence>
<sentence id="S6">There was evidence for <coref min="form" id="C9">an autosomal recessive form of inheritance</coref> in four families, while <coref min="families" id="C10">the other four families</coref> appeared to have <coref min="mode" id="C11">an autosomal dominant mode of transmission</coref>.</sentence>
<sentence id="S7">In three families <coref ref="C9" min="form" type="IDENT" id="C12">the autosomal recessive form</coref> was characterized by normal receptor as well as hormone data in both parents, while in one family receptor levels in both parents were greatly reduced, but hormone levels were normal.</sentence>
<sentence id="S8">In <coref ref="C10" min="families" type="IDENT" id="C13">the four families with <coref ref="C11" min="mode" type="IDENT" id="C14">an autosomal dominant mode of transmission</coref></coref> there was always one parent with reduced receptor binding in <coref ref="C6" type="IDENT" id="C15">peripheral mononuclear leucocytes</coref> and elevated serum hormone levels.</sentence>
<sentence id="S9">These parents were entirely asymptomatic.</sentence>
<sentence id="S10">In an extended family we were able to study <coref id="C16"><coref id="C17">an aunt</coref> and <coref ref="C17" type="PRON" id="C18">her</coref> newborn daughter</coref>, <coref ref="C16" type="RELAT" id="C19">who</coref> were <coref ref="C16" type="PRON" id="C20">both</coref> also biochemically affected but clinically asymptomatic.</sentence>
<sentence id="S11">It, therefore, appears that this dual pattern of genetic transmission may indicate <coref ref="C3" min="defects" type="IDENT" id="C21"><coref min="defects" id="C22">differing genetic defects</coref> <coref ref="C22" type="RELAT" id="C23">which</coref> cause the same clinical picture of <coref ref="C4" type="IDENT" id="C24">pseudohypoaldosteronism</coref></coref>.</sentence>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>

=== mappauk/prompt-based-structured-inference/data/coref/GENIA_MedCo_coreference_corpus_1.0/test/8139041.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION COREF 1.0//EN" "GENIA_coref_10.dtd">
<?xml-stylesheet type="text/css" href="GENIA_coref_10.css"?>
<Annotation annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;amp;retmode=xml&amp;amp;rettype=medline&amp;amp;id=8139041">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>8139041</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">A transcriptional regulatory element is associated with <coref id="C1">a nuclease-hypersensitive site in the pol gene of <coref id="C2">human immunodeficiency virus type 1</coref></coref>.</sentence>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2">Analysis of the chromatin organization of <coref ref="C2" type="IDENT" id="C3">the integrated human immunodeficiency virus type 1 (HIV-1) genome</coref> has previously revealed <coref id="C4">a major constitutive DNase I-hypersensitive site</coref> associated with the pol gene (E. Verdin, J. Virol. 65:6790-6799, 1991).</sentence>
<sentence id="S3">In the present report, high-resolution mapping of <coref ref="C4" min="site" type="IDENT" id="C5">this site</coref> with DNase I and micrococcal nuclease identified a nucleosome-free region centered around nucleotides (nt) 4490 to 4766.</sentence>
<sentence id="S4"><coref id="C6">A 500-bp fragment</coref> encompassing <coref ref="C5" min="site" type="IDENT" id="C7">this hypersensitive site (nt 4481 to 4982)</coref> exhibited transcription-enhancing activity (two- to threefold) when <coref ref="C6" type="PRON" id="C8">it</coref> was cloned in <coref ref="C6" type="PRON" id="C9">its</coref> natural position with respect to the HIV-1 promoter after transient transfection in U937 and CEM cells.</sentence>
<sentence id="S5">Using in vitro footprinting and gel shift assays, we have identified four distinct binding sites for nuclear proteins within <coref ref="C6" type="IDENT" id="C10">this positive regulatory element</coref>.</sentence>
<sentence id="S6"><coref min="site" id="C11">Site B (nt 4519 to 4545)</coref> specifically bound four distinct nuclear protein complexes: a ubiquitous factor, a T-cell-specific factor, a B-cell-specific factor, and the monocyte/macrophage- and <coref id="C12">B-cell-specific transcription factor PU.1/Spi-1</coref>.</sentence>
<sentence id="S7">In <coref id="C13">most HIV-1 isolates</coref> in <coref ref="C13" type="RELAT" id="C14">which</coref> <coref id="C15">this PU box</coref> was not conserved, <coref ref="C15" type="PRON" id="C16">it</coref> was replaced by a binding site for the related factor Ets1.</sentence>
<sentence id="S8">Factors binding to site C (nt 4681 to 4701) had <coref id="C17">a DNA-binding specificity</coref> similar to <coref ref="C17" type="PRON" id="C18">that</coref> of factors binding to <coref ref="C11" type="IDENT" id="C19">site B</coref>, except for <coref ref="C12" type="IDENT" id="C20">PU.1/Spi-1</coref>.</sentence>
<sentence id="S9">A GC box containing a binding site for Sp1 was identified (nt 4623 to 4631).</sentence>
<sentence id="S10">Site D (nt 4816 to 4851) specifically bound a ubiquitously expressed factor.</sentence>
<sentence id="S11">These results identify a transcriptional regulatory element associated with <coref ref="C1" min="site" type="IDENT" id="C21">a nuclease-hypersensitive site in the pol gene of <coref ref="C2" type="IDENT" id="C22">HIV-1</coref></coref> and suggest that <coref ref="C22" type="PRON" id="C23">its</coref> activity may be controlled by a complex interplay of cis-regulatory elements.</sentence>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>

=== mappauk/prompt-based-structured-inference/data/coref/GENIA_MedCo_coreference_corpus_1.0/test/9191057.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION COREF 1.0//EN" "GENIA_coref_10.dtd">
<?xml-stylesheet type="text/css" href="GENIA_coref_10.css"?>
<Annotation annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;amp;retmode=xml&amp;amp;rettype=medline&amp;amp;id=9191057">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>9191057</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">Relief of cyclin A gene transcriptional inhibition during activation of <coref min="lymphocytes" id="C1">human primary T lymphocytes</coref> via <coref min="molecules" id="C2">CD2 and CD28 adhesion molecules</coref>.</sentence>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2">Cyclin A transcription is cell cycle regulated and induced by cell proliferative signals.</sentence>
<sentence id="S3">To understand the mechanisms underlined in this regulation in normal human cells, we have analysed in vivo protein-DNA interactions at the Cyclin A locus in <coref ref="C1" min="lymphocytes" type="IDENT" id="C3">primary T lymphocytes</coref>.</sentence>
<sentence id="S4">Stimulation of purified T lymphocytes by a combination of monoclonal antibodies directed at <coref ref="C2" min="molecules" type="IDENT" id="C4">CD2 and CD28 adhesion molecules</coref> gives rise to a long lasting proliferation in the absence of accessory cells.</sentence>
<sentence id="S5">Cyclin A was observed after 4 days of costimulation with <coref id="C5">anti CD2 + CD28</coref> whereas stimulation by <coref id="C6"><coref type="IDENT" id="C7">anti CD2</coref> or <coref type="IDENT" id="C8">anti CD28</coref> alone</coref> was not effective.</sentence>
<sentence id="S6">In vivo genomic DMS footprinting revealed upstream of the major transcription initiation sites, the presence of <coref min="sites" id="C9">at least three protein binding sites</coref>, <coref id="C10"><coref ref="C9" min="two" type="IDENT" id="C11"><coref id="C12">two</coref> of <coref ref="C12" type="RELAT" id="C13">which</coref></coref> were constitutively occupied</coref>.</sentence>
<sentence id="S7"><coref ref="C10" type="PRON" id="C14">They</coref> bind in vitro respectively ATF-1 and NF-Y proteins.</sentence>
<sentence id="S8"><coref ref="C9" min="site" type="IDENT" id="C15">The third site</coref> was occupied in <coref min="cells" id="C16">quiescent cells</coref> or in cells stimulated by <coref ref="C6" type="IDENT" id="C17"><coref ref="C7" type="IDENT" id="C18">anti CD2</coref> or <coref ref="C8" type="IDENT" id="C19">anti CD28</coref> alone</coref>.</sentence>
<sentence id="S9"><coref min="combination" id="C20">The mitogenic combination of <coref ref="C5" type="IDENT" id="C21">anti CD2 + anti CD28</coref></coref> released the footprint as cells were committed to proliferation.</sentence>
<sentence id="S10">Consistent with theses results, nuclear extracts prepared from <coref ref="C16" min="cells" type="IDENT" id="C22">quiescent cells</coref> formed a specific complex with <coref ref="C20" min="element" type="IDENT" id="C23">this element</coref>, whereas extracts prepared from cells treated with <coref ref="C21" type="IDENT" id="C24">anti CD2 + anti CD28</coref> failed to do so after cells entered a proliferative state.</sentence>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>

=== mappauk/prompt-based-structured-inference/data/coref/GENIA_MedCo_coreference_corpus_1.0/test/7858491.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION COREF 1.0//EN" "GENIA_coref_10.dtd">
<?xml-stylesheet type="text/css" href="GENIA_coref_10.css"?>
<Annotation annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;amp;retmode=xml&amp;amp;rettype=medline&amp;amp;id=7858491">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>7858491</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">Expression and genomic configuration of <coref id="C1">GM-CSF, IL-3, <coref min="receptor" id="C2">M-CSF receptor (C-FMS)</coref>, <coref id="C3">early growth response gene-1 (EGR-1)</coref> and <coref min="genes" id="C4">M-CSF genes</coref></coref> in <coref min="syndromes" id="C5">primary myelodysplastic syndromes</coref>.</sentence>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2">Peripheral blood mononuclear cells from <coref min="patients" id="C6">seventeen patients with <coref ref="C5" min="syndromes" type="IDENT" id="C7">primary myelodysplastic syndromes (MDS)</coref> in advanced stage</coref> were enriched for blasts and tested for <coref id="C8"><coref id="C9">(1) karyotype</coref>, (2) genomic configuration and (3) expression of <coref ref="C1" type="IDENT" id="C10">IL-3, GM-CSF, FMS and <coref ref="C3" min="genes" type="IDENT" id="C11">EGR-1 genes</coref></coref></coref> <coref ref="C8" type="RELAT" id="C12">which</coref> are all located on the long arm of chromosome 5.</sentence>
<sentence id="S3"><coref min="expression" id="C13">The expression of <coref ref="C4" min="gene" type="IDENT" id="C14">the M-CSF gene</coref></coref>, <coref ref="C13" type="RELAT" id="C15">that</coref> has been recently reassigned to the short arm of chromosome 1 (lp), was also investigated.</sentence>
<sentence id="S4">Aims of the study were to (1) assess the potential role of the expression of <coref ref="C10" min="genes" type="IDENT" id="C16">these genes</coref> in the maintenance and expansion of the neoplastic clones and (2) search for constitutional losses or rearrangements of one allele followed by a deletion of the second allele of <coref ref="C16" min="genes" type="IDENT" id="C17">the same genes</coref> in the leukemic cells.</sentence>
<sentence id="S5">The latter issue was investigated by comparing, in 8 cases, constitutive DNA from skin fibroblasts with leukemic DNA.</sentence>
<sentence id="S6">Eleven of <coref ref="C6" min="patients" type="IDENT" id="C18">the 17 patients</coref> had abnormal <coref ref="C9" type="IDENT" id="C19">karyotypes</coref>.</sentence>
<sentence id="S7"><coref ref="C14" min="gene" type="IDENT" id="C20">The M-CSF gene</coref> was expressed in 6 cases and <coref ref="C2" type="IDENT" id="C21">the FMS</coref> and <coref ref="C11" min="genes" type="IDENT" id="C22">the EGR-1 genes</coref> were expressed in <coref id="C23">2 of the latter cases</coref>.</sentence>
<sentence id="S8">An autocrine mechanism of growth could be hypothesized only for <coref ref="C23" min="patients" type="IDENT" id="C24">the 2 patients</coref> <coref ref="C24" type="RELAT" id="C25">whose</coref> cells expressed both the M-CSF and FMS genes.</sentence>
<sentence id="S9">No germline changes or rearrangements were observed in any of <coref ref="C10" min="genes" type="IDENT" id="C26">the genes</coref> studied.</sentence>
<sentence id="S10">Thus, deregulation of genes encoding for certain hemopoietic growth factors or receptors does not seem to represent a major mechanism of MDS progression.</sentence>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>

=== mappauk/prompt-based-structured-inference/data/coref/GENIA_MedCo_coreference_corpus_1.0/test/9632764.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION COREF 1.0//EN" "GENIA_coref_10.dtd">
<?xml-stylesheet type="text/css" href="GENIA_coref_10.css"?>
<Annotation annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;amp;retmode=xml&amp;amp;rettype=medline&amp;amp;id=9632764">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>9632764</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">Coactivation by <coref id="C1">OCA-B</coref>: definition of critical regions and synergism with general cofactors.</sentence>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2">Molecular dissection of <coref ref="C1" type="IDENT" id="C2">the B-cell-specific transcription coactivator OCA-B</coref> has revealed distinct regions important, respectively, for recruitment to immunoglobulin promoters through interaction with octamer-bound Oct-1 and for subsequent coactivator function.</sentence>
<sentence id="S3">Further analysis of general coactivator requirements showed that selective removal of <coref id="C3">PC4</coref> from the essential USA fraction severely impairs Oct-1 and OCA-B function in <coref min="system" id="C4">a cell-free system reconstituted with partially purified factors</coref>.</sentence>
<sentence id="S4">Full activity can be restored by the combined action of recombinant PC4 and the PC4-depleted USA fraction, thus suggesting a joint requirement for PC4 and another, USA-derived component(s) for optimal function of Oct-1/OCA-B in <coref ref="C4" min="system" type="IDENT" id="C5">the reconstituted system</coref>.</sentence>
<sentence id="S5">Indeed, USA-derived PC2 was found to act synergistically with <coref ref="C3" type="IDENT" id="C6">PC4</coref> in reproducing the function of intact USA in the assay system.</sentence>
<sentence id="S6">Consistent with the requirement for <coref ref="C6" type="IDENT" id="C7">PC4</coref> in <coref ref="C5" min="system" type="IDENT" id="C8">the reconstituted system</coref>, <coref ref="C2" type="IDENT" id="C9">OCA-B</coref> was found to interact directly with <coref ref="C7" type="IDENT" id="C10">PC4</coref>.</sentence>
<sentence id="S7">Surprisingly, however, removal of <coref ref="C10" type="IDENT" id="C11">PC4</coref> from the unfractionated nuclear extract has no detrimental effect on OCA-B/Oct-1-dependent transcription.</sentence>
<sentence id="S8">These results lead to a general model for the synergistic function of activation domains in Oct-1 and <coref ref="C9" type="IDENT" id="C12">OCA-B</coref> (mediated by the combined action of the multiple USA components) and, further, suggest a functional redundancy in general coactivators.</sentence>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>

=== mappauk/prompt-based-structured-inference/data/coref/GENIA_MedCo_coreference_corpus_1.0/test/8780159.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION COREF 1.0//EN" "GENIA_coref_10.dtd">
<?xml-stylesheet type="text/css" href="GENIA_coref_10.css"?>
<Annotation annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;amp;retmode=xml&amp;amp;rettype=medline&amp;amp;id=8780159">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>8780159</PMID>
<Article>
<ArticleTitle>
<sentence id="S1"><coref min="absence" id="C34">Absence of <coref id="C13">T-cell- and B-cell-specific transcription factors <coref id="C24">TCF-1</coref>, <coref id="C16">GATA-3</coref>, and <coref id="C21">BSAP</coref></coref> in <coref id="C4">Hodgkin's Reed-Sternberg cells</coref></coref>.</sentence>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2">Based on the presence of T cell receptor-beta (TcR-beta) gene rearrangements in L428 and HDLM-1 cells, the expression of <coref id="C27">CD2</coref> in HDLM-1 cells, and the presence of immunoglobulin heavy-chain (IgH) gene rearrangement in KM-H2 cells, some researchers have concluded that <coref min="cell lines" id="C1">these long-term cell lines derived from patients with Hodgkin's disease</coref> are lymphoid in nature.</sentence>
<sentence id="S3">The information obtained from <coref ref="C1" type="IDENT" id="C2">these cell lines</coref> has also been used in arguments for a lymphoid origin of <coref ref="C4" type="IDENT" id="C5">H-RS cells</coref> in tissue despite the frequent absence of lymphoid markers and Ig/TcR gene rearrangements in <coref ref="C2" type="IDENT" id="C3">these cells</coref>.</sentence>
<sentence id="S4">We questioned whether one can use the limited expression of <coref min="markers" id="C7">lymphoid markers</coref> or the limited gene rearrangement to conclude that <coref ref="C5" type="IDENT" id="C6">H-RS cells</coref> have a lymphoid origin, because <coref ref="C7" type="IDENT" id="C8">these markers</coref> may be aberrant in tumor cells.</sentence>
<sentence id="S5">In this study, we examined the expression of <coref ref="C13" type="IDENT" id="C12">two T-cell-specific transcription factors (TCF-1 and GATA-3) and one B-cell-specific transcription factor (BSAP)</coref> in cultured H-RS cells by using <coref min="aasay" id="C9">a gel mobility shift assay</coref>.</sentence>
<sentence id="S6">The sensitivity and specificity of <coref ref="C9" type="IDENT" id="C10">this assay</coref> for determination of cell lineage have been established in a large number of cultured human and murine cell lines.</sentence>
<sentence id="S7">All three types of <coref ref="C6" type="IDENT" id="C14">H-RS cell lines</coref> were consistently negative for <coref ref="C12" type="IDENT" id="C15"><coref ref="C21" type="IDENT" id="C22">BSAP</coref>, <coref ref="C24" type="IDENT" id="C23">TCF-1</coref>, and <coref ref="C16" type="IDENT" id="C17">GATA-3</coref></coref>.</sentence>
<sentence id="S8">The absence of <coref ref="C17" type="IDENT" id="C18">GATA-3</coref> was confirmed in <coref ref="C14" type="IDENT" id="C19">H-RS cells</coref> in tissues by an in situ hybridization technique.</sentence>
<sentence id="S9">Virtually all B-cell lines, with the exception of some myeloma cell lines, are positive for <coref ref="C22" type="IDENT" id="C20">BSAP</coref>, which is the transcription factor for promoters for several B-cell markers, including VpreB1, lambda 5, CD19, and CD20.</sentence>
<sentence id="S10">All T-cell lines tested were positive for <coref ref="C23" type="IDENT" id="C25">TCF-1</coref> and <coref ref="C17" type="IDENT" id="C26">GATA-3</coref>, which are the transcription factors for promoters for several T-cell-restricted markers, including <coref ref="C27" type="IDENT" id="C28">CD2</coref>, CD3, TcR, and lck.</sentence>
<sentence id="S11"><coref ref="C34" min="absence" type="IDENT" id="C35">The absence of <coref ref="C20" type="IDENT" id="C30">BSAP</coref>, <coref ref="C25" type="IDENT" id="C31">TCF-1</coref>, and <coref ref="C26" type="IDENT" id="C32">GATA-3</coref></coref> clearly indicates an underlying difference between <coref ref="C19" type="IDENT" id="C33">H-RS cells</coref> and lymphoid cells.</sentence>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>
