=== mappauk/prompt-based-structured-inference/data/coref/GENIA_MedCo_coreference_corpus_1.0/GENIA_coref_10.dtd
<!-- ============================================================ -->
<!-- DTD for Genia corpus with coref annotation                   -->
<!-- written by Jin-Dong KIM <jdkim@tsujii.is.s.u-tokyo.ac.jp>    -->
<!-- Date of last modification: August 1 2010                     -->
<!-- ============================================================ -->

<!-- ============================================================ -->
<!-- Labels for coref types                                       -->
<!-- ============================================================ -->

<!ENTITY % coref.type "(APPOS | IDENT | OTHERS | PRON | RELAT | PART-WHOLE | WHOLE-PART | OTHER)">

<!-- ============================================================ -->
<!-- HIERARCHICAL ELEMENTS                                        -->
<!-- ============================================================ -->
<!ELEMENT Annotation (PubmedArticleSet)>
<!ATTLIST Annotation
		annotates CDATA #IMPLIED
		creator   CDATA #IMPLIED
		created   CDATA #IMPLIED
>

<!ELEMENT PubmedArticleSet (PubmedArticle)>
<!ELEMENT PubmedArticle (MedlineCitation)>
<!ELEMENT MedlineCitation (PMID, Article)>
<!ELEMENT Article (ArticleTitle?, Abstract)>
<!ELEMENT Abstract (AbstractText)>

<!-- ============================================================ -->
<!-- BLOCK ELEMENTS                                               -->
<!-- ============================================================ -->
<!ELEMENT ArticleTitle (sentence)+>
<!ELEMENT AbstractText (sentence)+>
<!ELEMENT PMID (#PCDATA)>

<!-- ============================================================ -->
<!-- LINGUISTIC ELEMENTS                                          -->
<!-- ============================================================ -->
<!ELEMENT sentence	(#PCDATA | coref)*>
<!ATTLIST sentence	id ID	#REQUIRED>

<!ELEMENT coref (#PCDATA | coref)*>
<!ATTLIST coref
		id	ID		#REQUIRED
		ref	IDREFS		#IMPLIED
		type	%coref.type;	#IMPLIED
		min	CDATA		#IMPLIED
		target	CDATA		#IMPLIED
		check	CDATA		#IMPLIED
>

=== mappauk/prompt-based-structured-inference/data/coref/GENIA_MedCo_coreference_corpus_1.0/test/1911548.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION COREF 1.0//EN" "GENIA_coref_10.dtd">
<?xml-stylesheet type="text/css" href="GENIA_coref_10.css"?>
<Annotation annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;amp;retmode=xml&amp;amp;rettype=medline&amp;amp;id=1911548">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>1911548</PMID>
<Article>
<ArticleTitle>
<sentence id="S1"><coref min="nuclear factor" id="C1">A nuclear factor NF-GM2</coref> <coref ref="C1" type="RELAT" id="C2">that</coref> interacts with a regulatory region of <coref min="gene" id="C3">the GM-CSF gene</coref> essential for <coref ref="C1" type="PRON" id="C4">its</coref> induction in responses to <coref min="activation" id="C5"><coref id="C6">T-cell</coref> activation</coref>: purification from human T-cell leukemia line <coref ref="C6" type="IDENT" id="C7">Jurkat cells</coref> and similarity to <coref id="C8">NF-kappa B</coref>.</sentence>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2"><coref ref="C5" min="activation" type="IDENT" id="C9">Activation of <coref ref="C7" type="IDENT" id="C10">T cells</coref></coref> by antigen, lectin, or a combination of <coref id="C11">phorbol-12-myristate acetate (PMA) and calcium ionophore (A23187)</coref> leads to the induction of genes for a set of lymphokines, including <coref ref="C3" type="IDENT" id="C12">granulocyte-macrophage colony-stimulating factor (GM-CSF)</coref>.</sentence>
<sentence id="S3">We demonstrated in earlier studies that <coref min="region" id="C13">the upstream region of <coref min="promoter" id="C14">the mouse <coref ref="C12" type="IDENT" id="C15">GM-CSF</coref> promoter</coref> at positions between -95 and -73</coref> is essential for transcriptional activation in response to <coref ref="C11" type="IDENT" id="C16">PMA/A23187</coref>.</sentence>
<sentence id="S4"><coref ref="C13" type="IDENT" id="C17">This region</coref> contains <coref ref="C19" min="binding motifs" type="APPOS" id="C18">two DNA-binding motifs</coref>, <coref id="C19"><coref id="C20">GM2</coref> and <coref id="C21">GC-box</coref></coref>.</sentence>
<sentence id="S5"><coref min="sequence" id="C22">The <coref ref="C20" type="IDENT" id="C23">GM2</coref> sequence (GGTAGTTCCC)</coref> is recognized by <coref ref="C1" min="factor" type="IDENT" id="C24">an inducible factor NF-GM2</coref>; <coref id="C25">the <coref ref="C21" type="IDENT" id="C26">other</coref> (CCGCCC)</coref> by constitutive factors A1, A2, and B.</sentence>
<sentence id="S6">To elucidate <coref min="mechanism" id="C27">the mechanism of <coref ref="C15" min="gene" type="IDENT" id="C28">GM-CSF gene</coref> activation</coref>, we have purified <coref ref="C24" min="factor" type="IDENT" id="C29">the inducible factor NF-GM2</coref> from the nuclear extract of stimulated <coref ref="C10" type="IDENT" id="C30">Jurkat cells</coref> on the basis of specific DNA-binding activity.</sentence>
<sentence id="S7"><coref ref="C29" type="OTHER" id="C31">The purified NF-GM2</coref> consists of 50 <coref id="C32">(p50)</coref> and 65 kDa <coref id="C33">(p65)</coref> polypeptides and has a binding activity specific for both <coref ref="C28" type="IDENT" id="C34">the GM-CSF</coref> and immunoglobulin kappa (GGAAAGTCCC) enhancers.</sentence>
<sentence id="S8"><coref ref="C32" type="OTHER" id="C35">Electrophoretically purified p50</coref> alone can form <coref min="complex" id="C36">a protein-DNA complex</coref>, but in the mixture, <coref ref="C32" type="IDENT" id="C37">p50</coref> associates preferentially with <coref ref="C33" type="IDENT" id="C38">p65</coref> to form <coref min="complex" id="C39">the <coref ref="C29" type="IDENT" id="C40">NF-GM2</coref> complex</coref>.</sentence>
<sentence id="S9">In addition, <coref ref="C38" type="IDENT" id="C41">p65</coref> gave per se, with low affinity, <coref ref="C36" min="complex" type="IDENT" id="C42">a protein-DNA complex</coref> <coref ref="C42" type="RELAT" id="C43">that</coref> migrated more slowly than <coref ref="C39" min="complex" type="IDENT" id="C44">native <coref ref="C40" type="IDENT" id="C45">NF-GM2</coref> complex</coref>.</sentence>
<sentence id="S10">Furthermore, an antiserum against KBF1 (identical to 50 kDa NF-kappa B protein) reacted with <coref ref="C37" type="IDENT" id="C46">the p50</coref> of <coref ref="C45" type="IDENT" id="C47">NF-GM2</coref>, indicating that the NF-GM2 polypeptide cannot be immunologically differentiated from the 50 kDa subunit of <coref ref="C8" type="IDENT" id="C48">NF-kappa B</coref>.</sentence>
<sentence id="S11"><coref ref="C31" type="IDENT" id="C49">The purified NF-GM2</coref> activated in vitro transcription from <coref min="enhancer" id="C50">the kappa B enhancer</coref>, while <coref ref="C49" type="PRON" id="C51">it</coref> failed to stimulate transcription from <coref ref="C14" min="promoter" type="IDENT" id="C52">the <coref ref="C34" type="IDENT" id="C53">GM-CSF</coref> promoter</coref> harboring <coref ref="C22" min="sequence" type="IDENT" id="C54">the <coref ref="C23" type="IDENT" id="C55">GM2</coref> sequence</coref>.</sentence>
<sentence id="S12">This suggests that <coref ref="C27" min="activation mechanism" type="IDENT" id="C56"><coref id="C57">the activation mechanism</coref> of <coref ref="C53" min="gene" type="IDENT" id="C58">the GM-CSF gene</coref></coref> through the <coref ref="C55" type="IDENT" id="C59">GM2</coref>/<coref ref="C25" min="sequence" type="IDENT" id="C60"><coref ref="C26" type="IDENT" id="C61">GC-box</coref> sequence</coref> is different from <coref ref="C57" type="PRON" id="C62">that</coref> of genes carrying <coref ref="C50" min="enhancer" type="IDENT" id="C63">the kappa B enhancer</coref> alone.</sentence>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>

=== mappauk/prompt-based-structured-inference/data/coref/GENIA_MedCo_coreference_corpus_1.0/test/10206480.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION COREF 1.0//EN" "GENIA_coref_10.dtd">
<?xml-stylesheet type="text/css" href="GENIA_coref_10.css"?>
<Annotation annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;amp;retmode=xml&amp;amp;rettype=medline&amp;amp;id=10206480">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>10206480</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">Amelioration of <coref min="pancreatitis" id="C1">rat cerulein pancreatitis</coref> by <coref min="peptide" id="C2">guamerin-derived peptide</coref>, <coref ref="C2" min="inhibitor" type="APPOS" id="C3">a novel elastase inhibitor</coref>.</sentence>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2">Increased activity of various proteases is observed in both human and experimental pancreatitis; however, the information on the effects of specific protease inhibitors on the disease is limited.</sentence>
<sentence id="S3">In this study we show that <coref ref="C2" min="inhibitor" type="IDENT" id="C4">a novel elastase inhibitor</coref>, <coref ref="C4" min="peptide" type="APPOS" id="C5">guamerin-derived synthetic peptide (GDSP)</coref>, improves the parameters of cerulein-induced acute pancreatitis in the rat.</sentence>
<sentence id="S4">The effects of <coref ref="C4" type="IDENT" id="C6">GDSP</coref> on pancreatic weight, serum amylase and lipase, morphologic changes in the pancreas, <coref min="infiltration" id="C7">neutrophil infiltration</coref>, and nuclear factor KB (NF-KB) activation were measured in rats infused with supramaximal dose of <coref id="C8">cerulein</coref> (5 (g/kg/h) for 6 h.</sentence>
<sentence id="S5"><coref min="effects" id="C9">The effects of <coref ref="C6" type="IDENT" id="C10">GDSP</coref></coref> were also measured on superoxide formation by activated human neutrophils.</sentence>
<sentence id="S6"><coref ref="C9" min="effects" type="IDENT" id="C11"><coref id="C12">The effects</coref> of <coref ref="C10" type="IDENT" id="C13">GDSP</coref></coref> were compared with <coref ref="C12" type="PRON" id="C14">those</coref> of <coref min="inhibitor" id="C15">another elastase inhibitor</coref>, <coref ref="C15" type="APPOS" id="C16">elastatinal</coref>.</sentence>
<sentence id="S7"><coref ref="C13" type="IDENT" id="C17">GDSP</coref> significantly inhibited edema formation, <coref ref="C7" min="infiltration" type="IDENT" id="C18">neutrophil infiltration</coref>, acinar cell damage, and plasma lipase and amylase increases caused by <coref ref="C8" type="IDENT" id="C19">cerulein</coref>.</sentence>
<sentence id="S8"><coref ref="C17" type="IDENT" id="C20">GDSP</coref> also completely inhibited superoxide formation in the human neutrophils stimulated by N-formyl-methionine-leucine-phenyl-alanine (fMLP) or 12-O-tetradecanoylphorbol-13-acetate (TPA).</sentence>
<sentence id="S9"><coref ref="C15" type="IDENT" id="C21">Elastatinal</coref> had some of the same effects as <coref ref="C20" type="IDENT" id="C22">GDSP</coref> but was less potent and effective.</sentence>
<sentence id="S10">These results demonstrate a beneficial effect of <coref ref="C22" type="IDENT" id="C23">GDSP</coref>, <coref ref="C23" min="inhibitor" type="APPOS" id="C24">a novel specific elastase inhibitor</coref>, on the development of <coref ref="C1" min="pancreatitis" type="IDENT" id="C25">rat cerulein pancreatitis</coref>.</sentence>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>

=== mappauk/prompt-based-structured-inference/data/coref/GENIA_MedCo_coreference_corpus_1.0/test/8622971.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION COREF 1.0//EN" "GENIA_coref_10.dtd">
<?xml-stylesheet type="text/css" href="GENIA_coref_10.css"?>
<Annotation annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;amp;retmode=xml&amp;amp;rettype=medline&amp;amp;id=8622971">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>8622971</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">cAMP inducibility of <coref id="C1">transcriptional repressor ICER</coref> in developing and mature human T lymphocytes [published erratum appears in Proc Natl Acad Sci U S A 1996 Jul 23;93(15):8154]</sentence>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2">Stimulation of the <coref id="C2">cAMP-</coref>dependent signaling pathway exerts an inhibitory effect on the proliferation and effector functions of <coref id="C3">T cells</coref>.</sentence>
<sentence id="S3">The ability of <coref ref="C3" type="IDENT" id="C4">T cells</coref> to form high intracellular levels of <coref ref="C2" type="IDENT" id="C5">cAMP</coref> is acquired during development in the human thymus and is retained by the majority of mature peripheral T lymphocytes.</sentence>
<sentence id="S4">Here we show that elevated cAMP levels in <coref ref="C4" type="IDENT" id="C6">T cells</coref> correlate with the expression of <coref ref="C1" type="IDENT" id="C7">the potent transcriptional repressor ICER</coref> (inducible cAMP early repressor) previously described in the hypothalamic-pituitary-gonadal axis.</sentence>
<sentence id="S5">Further, in transcriptional assays in vivo, <coref ref="C1" type="IDENT" id="C8">ICER</coref> inhibits calcineurin-mediated expression of the interleukin 2 promoter as well as Tax-mediated transactivation of the human T-lymphotropic virus type I (HTLV-I) promoter.</sentence>
<sentence id="S6">Thus, the induction of <coref ref="C8" type="IDENT" id="C9">ICER</coref> in <coref ref="C6" type="IDENT" id="C10">T cells</coref> may play an important role in the <coref ref="C5" type="IDENT" id="C11">cAMP-</coref>induced quiescence and the persistent latency of HTLV-I.</sentence>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>

=== mappauk/prompt-based-structured-inference/data/coref/GENIA_MedCo_coreference_corpus_1.0/test/9363920.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION COREF 1.0//EN" "GENIA_coref_10.dtd">
<?xml-stylesheet type="text/css" href="GENIA_coref_10.css"?>
<Annotation annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;amp;retmode=xml&amp;amp;rettype=medline&amp;amp;id=9363920">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>9363920</PMID>
<Article>
<ArticleTitle>
<sentence id="S1"><coref min="activation" id="C1">The activation of the JAK2/STAT5 pathway</coref> is commonly involved in signaling through the human IL-5 receptor.</sentence>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2">The JAK (Janus kinase) family of protein tyrosine kinases and the STATs (signal transducers and activators of transcription) have been shown to be activated in response to a number of cytokines and growth factors.</sentence>
<sentence id="S3">In this study, we evaluated the activation of JAK/STAT pathway upon human interleukin-5 (hIL-5) stimulation of <coref id="C2"><coref min="cell lines" id="C3">two different hIL-5-responsive cell lines</coref>, <coref ref="C3" type="APPOS" id="C4">hIL-5 receptor alpha-subunit (hIL-5R alpha) cDNA-transfected TF-1 (TF-h5R alpha) and butyric-acid-treated YY-1 (YY-Bu)</coref>, and <coref min="eosinophils" id="C5">peripheral eosinophils</coref></coref>.</sentence>
<sentence id="S4">Immunoprecipitation and electrophoretic mobility shift analysis revealed that tyrosine phosphorylation of JAK2 and activation of STAT5 were induced upon stimulation with hIL-5 in <coref ref="C2" min="types" type="IDENT" id="C6">all three cell types</coref>, while STAT1 activation was only observed in <coref ref="C5" type="IDENT" id="C7">eosinophils</coref>.</sentence>
<sentence id="S5">These results indicate that <coref ref="C1" min="activation" type="IDENT" id="C8">JAK2/STAT5 activation</coref> is a common JAK/STAT pathway for hIL-5-mediated signal in <coref ref="C2" min="cells" type="IDENT" id="C9">these cells</coref>.</sentence>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>

=== mappauk/prompt-based-structured-inference/data/coref/GENIA_MedCo_coreference_corpus_1.0/test/7887301.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION COREF 1.0//EN" "GENIA_coref_10.dtd">
<?xml-stylesheet type="text/css" href="GENIA_coref_10.css"?>
<Annotation annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;amp;retmode=xml&amp;amp;rettype=medline&amp;amp;id=7887301">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>7887301</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">Cloning and characterization of <coref id="C1">NF-ATc</coref> and <coref id="C2">NF-ATp</coref>: <coref min="components" id="C3">the cytoplasmic components of NF-AT</coref>.</sentence>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2">Present evidence indicates <coref min="pathway" id="C4">a pathway of signal transmission in T cells</coref> <coref ref="C4" type="RELAT" id="C5">that</coref> is outlined in figure 1.</sentence>
<sentence id="S3">The elevation in <coref id="C6">intracellular calcium</coref> <coref ref="C6" type="RELAT" id="C7">that</coref> is induced by interactions at the antigen receptor leads to the activation of <coref min="calcineurin" id="C8">the calcium-dependent phosphatase calcineurin</coref>.</sentence>
<sentence id="S4">This in turn leads to the nuclear association of the cytosolic component of <coref ref="C1" type="IDENT" id="C9">NF-ATc</coref>.</sentence>
<sentence id="S5">The activation of <coref ref="C8" type="IDENT" id="C10">calcineurin</coref> and <coref min="import" id="C11">the nuclear import of <coref ref="C9" type="IDENT" id="C12">NF-ATc</coref></coref> can both be blocked by <coref id="C13">cyclosporin A or FK506</coref> in complex with <coref ref="C13" type="PRON" id="C14">their</coref> respective immunophilins.</sentence>
<sentence id="S6">Once in the nucleus, <coref ref="C12" type="IDENT" id="C15">NF-ATc</coref> interacts with <coref id="C16">NF-ATn</coref> to form an active transcriptional complex.</sentence>
<sentence id="S7"><coref ref="C16" type="IDENT" id="C17">NF-ATn</coref> is a ubiquitous protein, can be synthesized in response to PMA, and has many similarities to AP-1.</sentence>
<sentence id="S8"><coref id="C18">The mechanism</coref> by <coref ref="C18" type="RELAT" id="C19">which</coref> <coref ref="C15" type="IDENT" id="C20">NF-ATc</coref> enters the nucleus is unknown, and although it appears to require <coref ref="C10" type="IDENT" id="C21">calcineurin</coref>, <coref ref="C20" type="IDENT" id="C22">NF-ATc</coref> has not yet been shown to be an in vivo substrate of <coref ref="C21" type="IDENT" id="C23">calcineurin</coref>.</sentence>
<sentence id="S9">Alternative mechanisms include <coref id="C24">the possibility</coref> <coref ref="C24" type="RELAT" id="C25">that</coref> <coref ref="C22" type="IDENT" id="C26">NF-ATc</coref> operates on some cytoplasmic anchor or <coref ref="C24" type="RELAT" id="C27">that</coref> <coref id="C28">other proteins</coref> <coref ref="C28" type="RELAT" id="C29">that</coref> are controlled by calcineurin carry out <coref ref="C11" min="import" type="IDENT" id="C30">the nuclear import of <coref ref="C26" type="IDENT" id="C31">NF-ATc</coref></coref>.</sentence>
<sentence id="S10">Although <coref ref="C2" type="IDENT" id="C32">NF-ATp</coref> copurifies with <coref ref="C31" type="IDENT" id="C33">NF-ATc</coref>, there is as yet no understanding of how <coref ref="C32" type="IDENT" id="C34">NF-ATp</coref> is functioning in vivo.</sentence>
<sentence id="S11">Now that <coref ref="C3" type="IDENT" id="C35">these proteins</coref> are purified and cloned, the major goals will be to understand <coref ref="C35" type="PRON" id="C36">their</coref> role and the roles of other family members in thymic development.</sentence>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>

=== mappauk/prompt-based-structured-inference/data/coref/GENIA_MedCo_coreference_corpus_1.0/test/7645237.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION COREF 1.0//EN" "GENIA_coref_10.dtd">
<?xml-stylesheet type="text/css" href="GENIA_coref_10.css"?>
<Annotation annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;amp;retmode=xml&amp;amp;rettype=medline&amp;amp;id=7645237">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>7645237</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">Restoration of <coref min="protein" id="C1">the Epstein-Barr virus ZEBRA protein</coref>'s capacity to disrupt latency by the addition of heterologous activation regions.</sentence>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2"><coref ref="C1" min="protein" type="IDENT" id="C2">The ZEBRA protein</coref> has a unique biological function among herpesviral proteins.</sentence>
<sentence id="S3">It is responsible for the disruption of Epstein-Barr virus (EBV) latency and the induction of the lytic cycle.</sentence>
<sentence id="S4"><coref id="C3">ZEBRA</coref> is <coref min="transcriptional-activator" id="C4">a bZIP transcriptional activator</coref> <coref ref="C4" type="RELAT" id="C5">which</coref> binds as a dimer to 7-bp response elements within EBV promoters and is directly involved in the stimulation of virus replication at the EBV lytic origin.</sentence>
<sentence id="S5">We have employed the ZEBRA/EBV biological system to test whether a heterologous activation domain can substitute for <coref min="domain" id="C6">another activation domain (the ZEBRA domain)</coref>.</sentence>
<sentence id="S6"><coref ref="C6" min="region" type="IDENT" id="C7">The ZEBRA activation region</coref> was replaced with the potent acid activation region from the herpes simplex virus VP16 protein or with the activation region of the EBV R protein.</sentence>
<sentence id="S7">Both chimeras were found to transactivate model and native promoters at equivalent or better levels than <coref ref="C3" type="IDENT" id="C8">ZEBRA</coref> <coref ref="C8" type="PRON" id="C9">itself</coref>.</sentence>
<sentence id="S8"><coref id="C10">Activation</coref> was not target- or cell-type dependent, nor was <coref ref="C10" type="PRON" id="C11">it</coref> dependent on the presence of virus.</sentence>
<sentence id="S9">These activation domains restored <coref ref="C8" type="IDENT" id="C12">ZEBRA</coref>'s ability to induce early antigen and to stimulate origin replication to <coref id="C13">levels</coref> <coref ref="C13" type="RELAT" id="C14">that</coref> were equal to or greater than <coref ref="C13" type="PRON" id="C15">those</coref> of wild type.</sentence>
<sentence id="S10">These studies suggest that the specificities of some of the known biological functions of <coref ref="C12" type="IDENT" id="C16">ZEBRA</coref> are not dependent upon the nature of the activation domain present within <coref ref="C16" type="IDENT" id="C17">ZEBRA</coref>.</sentence>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>

=== mappauk/prompt-based-structured-inference/data/coref/GENIA_MedCo_coreference_corpus_1.0/test/1865413.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION COREF 1.0//EN" "GENIA_coref_10.dtd">
<?xml-stylesheet type="text/css" href="GENIA_coref_10.css"?>
<Annotation annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;amp;retmode=xml&amp;amp;rettype=medline&amp;amp;id=1865413">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>1865413</PMID>
<Article>
<ArticleTitle>
<sentence id="S1"><coref min="receptors" id="C1"><coref id="C2">Glucocorticoid</coref> receptors</coref> in <coref id="C3">systemic lupus erythematosus</coref>.</sentence>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2"><coref ref="C2" type="IDENT" id="C4">Glucocorticosteroids</coref> remain the major treatment modality for <coref ref="C3" type="IDENT" id="C5">systemic lupus erythematosus (SLE)</coref>, but <coref ref="C4" type="PRON" id="C6">their</coref> mechanism of action is unclear.</sentence>
<sentence id="S3">Over the past decade it has become clear that <coref ref="C1" min="receptors" type="IDENT" id="C7"><coref ref="C4" type="IDENT" id="C8">glucocorticosteroid</coref> receptors</coref> play a significant role in the mechanism of glucocorticosteroid action.</sentence>
<sentence id="S4">We studied glucocorticosteroid receptor density and affinity on peripheral blood mononuclear cells by the glucocorticosteroid binding assay in <coref min="patients" id="C9">33 patients with <coref ref="C5" type="IDENT" id="C10">SLE</coref></coref> <coref ref="C9" type="RELAT" id="C11">who</coref> had taken no <coref ref="C8" type="IDENT" id="C12">glucocorticosteroid</coref> for the previous 6 months and in <coref min="controls" id="C13">32 healthy controls</coref>.</sentence>
<sentence id="S5"><coref id="C14">Patients' disease activity</coref> was measured by the SLE Disease Activity Index (SLEDAI).</sentence>
<sentence id="S6"><coref ref="C7" min="receptors" type="IDENT" id="C15"><coref ref="C12" type="IDENT" id="C16">Glucocorticosteroid</coref> receptors</coref> on leukocytes of <coref ref="C9" min="patients" type="IDENT" id="C17">patients with <coref ref="C10" type="IDENT" id="C18">SLE</coref></coref> were significantly higher than in <coref ref="C13" min="controls" type="IDENT" id="C19">healthy controls</coref> (4419 +/- 306 vs 3369 +/- 196, p less than 0.005).</sentence>
<sentence id="S7">The binding affinity was not different between <coref ref="C17" type="IDENT" id="C20">patients</coref> and <coref ref="C19" type="IDENT" id="C21">controls</coref>.</sentence>
<sentence id="S8">There was no correlation between glucocorticosteroid receptor number and <coref ref="C14" type="IDENT" id="C22">SLE disease activity</coref>.</sentence>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>

=== mappauk/prompt-based-structured-inference/data/coref/GENIA_MedCo_coreference_corpus_1.0/test/9388475.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION COREF 1.0//EN" "GENIA_coref_10.dtd">
<?xml-stylesheet type="text/css" href="GENIA_coref_10.css"?>
<Annotation annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;amp;retmode=xml&amp;amp;rettype=medline&amp;amp;id=9388475">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>9388475</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">Molecular cloning and functional characterization of murine cDNA encoding transcription factor NFATc.</sentence>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2">Transcription factors of the NFAT (nuclear factor of activated T cells) family play important roles in immune and inflammatory responses by regulating the expression of genes encoding cytokines and immunoregulatory proteins.</sentence>
<sentence id="S3">Here we describe cloning and characterization of <coref min="cdna" id="C1">full-length cDNA encoding <coref id="C2">murine (m) NFATc</coref></coref> <coref ref="C1" type="RELAT" id="C3">which</coref> predicts that the protein has all the conserved structural motifs of NFAT family members, including the rel homology domain, the NFAT homology domain and the nuclear translocation signals.</sentence>
<sentence id="S4"><coref ref="C2" type="IDENT" id="C4">mNFATc</coref> complexed with AP-1 bound specifically to the murine IL-2 NFAT recognition sequence and activated transcription from the co-transfected IL-2 promoter in COS-7 cells.</sentence>
<sentence id="S5">Northern blot analysis showed that the cDNA probe hybridized with <coref min="transcript" id="C5">a 4.5 kb transcript</coref> <coref ref="C5" type="RELAT" id="C6">which</coref> is highly inducible in murine T cells.</sentence>
<sentence id="S6">By Northern and in situ hybridization, <coref min="transcript" id="C7">mNFATc transcript</coref> was detected from the early stage of development.</sentence>
<sentence id="S7">In the mouse embryo, <coref ref="C7" min="transcript" type="IDENT" id="C8">mNFATc transcript</coref> was strongly expressed in thymus, lung and submandibular gland and weakly in skeletal muscle and heart suggesting that <coref ref="C4" type="IDENT" id="C9">mNFATc</coref> may have a role both in embryogenesis and in mature T cells.</sentence>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>
